### PR TITLE
Fix is_market_listed() on multi pane layouts

### PR DESCRIPTION
**Pull request by mrcrdwd**
Checking on the price axis doesn't work when the chart layout has multiple panes. Checking for the invalid symbol does.

### CODE REVIEW

**Comment by timelyart** [comment]
Old code seem to work fine for me.

Are you using a multi pane layout for backtesting?

**Comment by mrcrdwd** [comment]
> Are you using a multi pane layout for backtesting?

Yes. I use an external indicator on the second pane.

**Comment by timelyart** [comment]
So, I have been able to reproduce this when using multiple panes and the first one not being the price chart.

The reason why I choose to look at the price axes is because this will work with a multiple chart layout with different symbols. 
So, a solution where this will stay intact is preferred.

**Comment by timelyart** [comment]
I came up with different solution more akin to how the method was intended.

**Pull request closed without merging**
