### PR TITLE
Update tv.py to fix an import bug

### PR DESCRIPTION
**Pull request by modanesh**

### CODE REVIEW

**Comment by timelyart** [comment]
What is the import bug exactly? It seems to resolve just fine.

**Comment by modanesh** [comment]
It gave me this error: `module mail has no attribute send_admin_message` so I had to change that line to resolve the issue.

**Comment by timelyart** [comment]
Do you have a different _mail.py_ installed? Do you use virtual environments?

The line `from tv import mail` gives me a warning _Import resolves to its containing file_.

**Comment by modanesh** [comment]
I use virtual env and have no `mail` installed. Other imports similar to `from tv import mail` work fine so I changed that line to resolve the issue.

**Comment by timelyart** [comment]
Ah, you are right. Seems I suppress the warning in the other cases. 

Thank you for your contribution!

**Pull request merged**
